/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "surface-variant": "#2d3449",
            "tertiary": "#4edea3",
            "on-tertiary": "#003824",
            "inverse-surface": "#dae2fd",
            "on-primary-fixed-variant": "#004395",
            "outline-variant": "#424754",
            "error": "#ffb4ab",
            "on-primary-fixed": "#001a42",
            "error-container": "#93000a",
            "primary-container": "#4d8eff",
            "text-secondary": "#cbd5e1",
            "on-primary": "#002e6a",
            "surface-bright": "#31394d",
            "on-surface-variant": "#c2c6d6",
            "surface-main": "#0f172a",
            "tertiary-fixed": "#6ffbbe",
            "surface-container": "#1e293b",
            "on-secondary-container": "#a7b6cc",
            "surface-container-lowest": "#060e20",
            "outline": "#8c909f",
            "on-secondary-fixed-variant": "#39485a",
            "secondary-fixed": "#d4e4fa",
            "inverse-on-surface": "#283044",
            "on-tertiary-fixed": "#002113",
            "secondary-fixed-dim": "#b9c8de",
            "primary": "#adc6ff",
            "tertiary-container": "#00a572",
            "primary-fixed": "#d8e2ff",
            "primary-fixed-dim": "#adc6ff",
            "on-secondary-fixed": "#0d1c2d",
            "surface-tint": "#adc6ff",
            "on-primary-container": "#00285d",
            "on-secondary": "#233143",
            "text-primary": "#f8fafc",
            "surface-dim": "#0b1326",
            "secondary": "#b9c8de",
            "surface-container-high": "#222a3d",
            "surface-container-low": "#131b2e",
            "surface": "#0b1326",
            "secondary-container": "#39485a",
            "on-background": "#dae2fd",
            "on-tertiary-fixed-variant": "#005236",
            "on-error-container": "#ffdad6",
            "on-tertiary-container": "#00311f",
            "border-subtle": "#334155",
            "surface-container-highest": "#2d3449",
            "on-error": "#690005",
            "tertiary-fixed-dim": "#4edea3",
            "on-surface": "#dae2fd",
            "inverse-primary": "#005ac2",
            "background": "#0b1326"
        },
        "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
        },
        "spacing": {
            "base": "8px",
            "margin-tablet": "40px",
            "gutter-desktop": "24px",
            "stack-xl": "64px",
            "stack-lg": "32px",
            "gutter-mobile": "16px",
            "container-max": "1280px",
            "stack-sm": "8px",
            "stack-md": "16px"
        },
        "fontFamily": {
            "body-md": ["Inter"],
            "headline-lg-mobile": ["Geist"],
            "body-lg": ["Inter"],
            "headline-md": ["Geist"],
            "headline-lg": ["Geist"],
            "headline-sm": ["Geist"],
            "label-md": ["Geist"]
        },
        "fontSize": {
            "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
            "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
            "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
            "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
            "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
            "label-md": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }]
        }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
